application: sample-app
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: main.app

builtins:
- deferred: on

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: '2.6'